# Generated by Django 5.0.7 on 2024-08-05 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='dob',
        ),
    ]
