# Generated by Django 5.0.7 on 2024-08-06 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_students_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=500)),
                ('car_speed', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
